inventus_bmu_node:
  ros__parameters:
    can_device: can0
    module_ids: [49, 50]

    # List of module IDs that are connected in series in string format
    # Each series is in parallel with each other
    # Top level list is parallel, nested lists are series
    # This is used to calculate the total output voltage & current
    module_series: '[[49, 50]]'

