diagnostic_aggregator:
  ros__parameters:
    path: Clearpath Diagnostics
    platform:
      type: diagnostic_aggregator/AnalyzerGroup
      path: Platform
      analyzers:
        power:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Power
          contains: [ 'Battery', 'Power' ]
        stop_status:
          type: diagnostic_aggregator/GenericAnalyzer
          path: E-stop Status
          contains: [ 'E-stop' ]
        mcu:
          type: diagnostic_aggregator/GenericAnalyzer
          path: MCU
          contains: [ 'MCU' ]
        lighting:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Lighting
          contains: [ 'Light' ]
        motor_drivers:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Motor Drivers
          contains: [ 'Lynx' ]
    # sensors:
    #   type: diagnostic_aggregator/AnalyzerGroup
    #   path: Sensors
    #   analyzers: # Must be populated with the sensor categories
