name: clearpath_robot_ci

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  clearpath_robot_ci:
    name: Humble
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: humble

          package-name: clearpath_robot
          vcs-repo-file-url: dependencies.repos
